SET DEFINE OFF;
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('1904.30.00', 'BULGUR WHEAT', 25, 30, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3206.11.00', 'Pigments & Preparatns Based On Titanium Dioxide,Cont.=>80%Titanium Dioxide', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3206.19.10', 'Pigments/Preparatns Based On Titanium Dioxide, Cont.< 80% Titanium Dioxide', 15, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3206.19.20', 'Color master batch', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3206.19.90', 'Pigments/Preparatns Based On Titanium Dioxide, Cont.< 80% Titanium Dioxide', 15, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3206.20.00', 'Pigments And Preparations Based On Chromium Compounds', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3206.41.00', 'Ultramarine And Preparations Based On Other Colouring Matter', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3206.42.00', 'Lithopone And Other Pigments And Preparations Based On Zinc Sulphide', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3206.49.00', 'Other Colouring Matter; Preparations As Specified In Note 3, Nes', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3206.50.00', 'Inorganic Products Of A Kind Used As Luminophores', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3207.10.00', 'Prepared Pigments, Opacifiers & Colours... For Ceramics And Glass Ind.Etc', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3207.20.00', 'Vitrifiable Enamels And Glazes, Englobes And Similar Preparations', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3207.30.00', 'LIQUID LUSTRES AND SIMILAR PREPARATIONS', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3207.40.00', 'GLASS FRIT AND OTHER GLASS,IN THE FORM OF GRANULES OR FLAKES', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3208.10.10', 'Paints & Varnishes Imp.by B.Biman,Flying Club,Concern Govt.Dept.& VAT Regd.Mfg...', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3208.10.20', 'Insulating varnish for copper wire', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3208.10.90', 'Other Paints Based On Polyesters, In A Non-Aqueous Medium', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3208.20.10', 'Paints & Varnishes Imp.by B.Biman,Flying Club,Concern Govt.Dept.& VAT Regd.Mfg...', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3208.20.91', 'Other Paints Based On Acrylic Or Vinyl Polymers, In A Non-Aqueous Medium', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3208.20.99', 'Other Paints Based On Acrylic Or Vinyl Polymers, In A Non-Aqueous Medium', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3208.90.10', 'Paints & Varnishes Imp.by B.Biman,Flying Club,Concern Govt.Dept.& VAT Regd.Mfg...', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3208.90.20', 'Heat Sealable Lacquers', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3208.90.30', 'Coating materials imported by VAT registered cookingware manufacturers', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3208.90.90', 'Other Paints And Varnishes, In A Non-Aqueous Medium, Nes', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3209.10.10', 'Paints & Varnishes Imp.by B.Biman,Flying Club,Concern Govt.Dept.& VAT Regd.Mfg...', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3209.10.90', 'Other Paints Based On Acrylic Or Vinyl Polymers, In An Aqueous Medium', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3209.90.10', 'Paints & Varnishes Imp.by B.Biman,Flying Club,Concern Govt.Dept.& VAT Regd.Mfg...', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3209.90.20', 'Heat Sealable Lacqers', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3209.90.30', 'Coating materials imported by VAT registered cookingware manufacturers', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3209.90.90', 'Other Paints And Varnishes, In An Aqueous Medium, Nes', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3210.00.10', 'Paints & Varnishes Imp.by B.Biman,Flying Club,Concern Govt.Dept.& VAT Regd.Mfg...', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('5205.26.00', 'Com.Sin.Cot.Yarn,With>=85%Cot.,Nprs,<125 De.But >=106.38>80mn But<=94mm', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('3506.99.00', 'Stripping chemical', 5, 0, 15, 
    5, 15, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4410.12.00', 'Oriented standard board (OSB)', 25, 10, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4410.19.00', 'Particle board, ori. strand board (OSB) and si. board, Exclu.Particle&Oriented', 25, 10, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4011.90.00', 'Other Tyre, excl. construction, mining or industrial handling vehicles and machines', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4012.11.00', 'OF A KIND USED ON MOTOR CARS(INCL.STATION WAGONS & RACING CARS)', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4012.12.00', 'OF A KIND USED ON BUSES OR LORRIES', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4012.13.00', 'OF A KIND USED ON AIRCRAFT', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4012.19.00', 'RETREADED OR USED PNMATIC.TYRES OF RUBBER;SOLID OR CUSHION TYRES,TYRE..NES', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4012.20.00', 'Used Pneumatic Tyres Of Rubber', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4012.90.10', 'Tyre flaps of rubber of a kind used on tructor and aircraft', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4012.90.90', 'Solid... tyres, interchangeable tyre treads and flaps, of rubber, nes', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4013.10.00', 'INNER TUBES, OF RUBBER, OF A KIND USE ON MOTOR CARS(INCL.STN.WAGON..),BUSES OR LORRIE', 15, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4013.20.00', 'Inner Tubes, Of Rubber Of A Kind Used On Bicycles', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4013.90.10', 'Inner Tubes, of rubber Of a kind used on tractors and aircraft', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4013.90.20', 'Inner tube of rubber, of a kind used on motorcycles', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4013.90.90', 'Inner tubes, of rubber, nes', 15, 0, 15, 
    5, 5, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4014.10.00', 'Sheath Contraceptives Of Rubber', 0, 0, 0, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4014.90.00', 'Hygienic Or Pharmaceutical Articles Of Vulcanized Rubber, Nes', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4015.11.00', 'Surgical Gloves Of Rubber', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4015.19.00', 'Gloves Of Vulcanized Rubber (Excl. Surgical Gloves)', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4015.90.00', 'Articles Of Apparel And Clothing Accessories Of Vulcanized Rubber, Nes', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4016.10.00', 'Articles Of Vulcanized Cellular Rubber', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4016.91.00', 'Floor Coverings And Mats Of Vulcanized Rubber, Non-Cellular', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4016.92.00', 'Erasers, Of Vulcanized Rubber', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4016.93.00', 'Gaskets, Washers And Other Seals, Of Vulcanized Rubber', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4016.94.00', 'Boat Or Dock Fenders, Of Vulcanized Rubber', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4016.95.00', 'Inflatable Articles, Of Vulcanized Rubber, Nes', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4016.99.10', 'ARTICLES OF VULCANIZED RUBBER, RUBBER CO /APRON', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4016.99.20', 'Rubber bearing', 5, 0, 0, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4016.99.90', 'ARTICLES OF VULCANIZED RUBBER,NES EX.RUBBER COT/APRON', 5, 0, 15, 
    5, 20, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4017.00.00', 'HARD RUBBER(FOR EX.,EBONITE) IN ALL FORMS,INCL.WASTE AND SCRAP; ARTICLES OF HARD RUBBER', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4101.20.00', 'WHOLE HIDES & SKINS,UNSPLIT,OF A WEIGHT PER SKIN<8KG-SIMPLY DRIED,10KG-DRY SALTED,OR 16.', 5, 0, 0, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4101.50.00', 'WHOLE HIDES AND SKINS, OF A WEIGHT EXCEEDING 16KG', 5, 0, 0, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7208.27.90', 'F.ROLLED PROD..IN COILS,...,OF A THICK.<3MM EXCL VAT REG. T.FORMER & PRE.FAB.MANU.IND.', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7208.36.10', 'F.hot-rolled Imp by VAT reg. t.former, pre-fab. building & bicycle parts manu. ind.', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7208.36.90', 'OTH.IN COILS, NOT FUR..,THICK.>10MM, EXCL. IMP.BY VAT REG.T.FORMER & PRE.FAB.BDL.MANU.', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7208.37.10', 'F.hot-rolled Imp by VAT reg. t.former, pre-fab. building & bicycle parts manu. ind.', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7208.37.90', 'OTH.IN COILS,NOT FUR..,OF THICK>=4.75MM,<= =10MM,EXCL.IMP. BY VAT REG.T.FRMR &P.FAB.B.', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7208.38.10', 'F./hot-rolled .Imp. by VAT regd. T.Former & pre-fab. building manufac Ind.', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7208.38.90', 'OTH.IN COILS,NOT FUR..,OF THICK.3MM-4.75MM, EXCL.IMP.BY VAT REG.T.FRMR &PR.FAB.BLD M.IND', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('6811.82.00', 'Arti.of asbestos-cement, of cellu...Not cont.asbestos.Ottr sheets, panels, tile', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('6811.89.00', 'Arti of asb..Not containing asbestos, NES Other articles', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7208.39.80', 'OTH.IN COILS,NOT FUR..,THICK.OF <3MM,EXCL. IMP BY VAT REG.I/S.PROD,T.FRMR & PR.FAB B.M.I', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7208.40.10', 'F.Rolled ..Imp. by VAT registered , T.Frormer and pre-fab. building manufa Ind', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('8101.99.90', 'Tungsten filament imported by exclu. VAT reg. incandescent light bulb manu.', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('8102.10.00', 'Powders Of Molybdenum', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7208.40.90', 'NOT IN COILS,NOT FURTHER..WITH PATTERN IN RELIEF,EXCL.IMP.BY VAT REG.T.FRMR,PR.FAB.M.IND', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7208.51.10', 'F./h-rolled ..Imp. by VAT regd. transformer and pre-fabricated building manufac Ind.', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7208.51.90', 'OTH.NOT IN COILS,NOT FRTR..THICK.>10MM, EXCL.IMP.BY VAT REG.T.FRMR,PRE.FAB.BLD.MA.IND', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7208.52.10', 'Imp by VAT reg Transformer, pre-fabric building and prod. of Ch 72 & Ch 73 manu. ind.', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7208.52.90', 'OTH.NOT IN COILS, NOT FRTHER..THICK 4.75-10 MM,EXCL.IMP.BY VAT REG.I/S,M.CYCLE,PRE.FAB.', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7208.53.10', 'Imp by VAT reg Transformer, pre-fabric build and products of Ch 72 & Ch 73 manu. ind.', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7208.53.90', 'OTH.NOT IN COILS, NOT FURTHER..THICK 3MM- 4.75MM,EXCL.IMP.BY VAT REG. I/STL, PRE.FAB.M.', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7208.54.10', 'F./hot-rolled Imp by VAT regd, pre-fab. building & trans & ch.72 & ch.73 manu. ind.', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7208.54.90', 'OTH.NOT IN COILS, NOT FURTHER..THICK. <3MM, EXCL.IMP.BY VAT REG.I/S,MCYCL,T.FRMR,PR.FAB', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7208.90.10', 'F./Hot-rolIed.... Imp by VAT reg. t.former and pre-fab. building manu. ind.', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7208.90.90', 'OTHER, NES, EXCL.IMP.BY VAT REG.I/STL PRO. T.FORMR, PRE.FAB.BDLING MANU.IND.', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7209.15.00', 'Flat/Cold-Rolled Iron/Steel, In Coils, Width >=600mm, >=3mm Thick', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7209.16.00', 'Flat/Cold-Rolled Iron/Steel, In Coils, Width >=600mm, >1mm But <3mm Thick', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7209.17.00', 'Flat/Coldrolled Iron/Steel,In Coils,Width >=600mm, >=0.5mm But <=1mm Thick', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7209.18.00', 'Flat roll Prod. in coil not Fut. work.. Cold roll thickness <.5mm', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7209.25.00', 'Flat/Cold-Rolled Iron/Steel, Not In Coils, Width >=600mm, >=3mm Thick', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7209.26.00', 'Flat/Cold-Rolled Iron/Steel,Not In Coils,Width>=600mm, >1mm But<3mm Thick', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7209.27.00', 'Flat/Coldrolled Iron/Steel,Not In Coils,Wid>=600mm,>=0.5mm But <=1mm Thick', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7209.28.00', 'Flat/Cold-Rolled Iron/Steel, Not In Coils, Width >=600mm, < 0.5mm Thick', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7209.90.00', 'Flat/Coldrolled Iron/Non-Alloy Steel,Wid>=600mm,Not Clad,Plated/Coated Nes', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7210.11.00', 'Flatrolled Iron/Steel, Width>=600mm, >= 0.5mm Thick,Clad,Plated...With Tin', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7210.12.00', 'Flat-Rolled Iron/Steel, Width >=600mm, <0.5mm Thick, Plated... With Tin', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7210.20.00', 'Flat-Rolled Iron/Steel,Width>=600mm,Plated/Coated With Lead,Inc.Terneplate', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7210.30.00', 'Flat-Rolled Iron/Steel, Width >=600mm, Electro-Plated Or Coated With Zinc', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7210.41.00', 'Flatrolld Iron/Steel,Wid.>=600mm,Plated Wth Zinc(Exc.Electroplatd)Corrugtd', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7210.49.10', 'Flat rolled prod. of a thickness => 0.4 mm Imp.VAT reg. Refri. & Pre. Fab.bu.Industry', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7210.49.20', 'OTHERWISE PLATED OR COATED WITH ZINC... >=1.0 MM IMP. BY REG. PRE-FABR.BUID. MANU.IND', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7210.49.90', 'Flat rolled products, NES', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('7210.50.00', 'Rolled Iron/Steel,Width>=600mm,Plated With Chromium Oxides/Cr. & Cr Oxides', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4418.20.00', 'Doors And Their Frames And Thresholds, Of Wood', 25, 10, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0904.22.90', 'Fruits of the genus Capsicum...,: crushed or ground, EXCL. Wrapped/canned upto 2.5 Kg', 25, 0, 0, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0905.10.10', 'Vanilla, Neither crushed or ground, Wrapped/canned upto 2.5 Kg', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0905.10.90', 'Vanilla, Neither crushed or ground, EXCL. Wrapped/canned upto 2.5 Kg', 25, 0, 0, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0905.20.10', 'Vanilla, crushed or ground, Wrapped/canned upto 2.5 Kg', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0905.20.90', 'Vanilla, crushed or ground, EXCL. Wrapped/canned upto 2.5 Kg', 25, 0, 0, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0906.11.10', 'Neither crushed nor ground:Cinnamon (Cinnamomum zeylanicum Blume), Wr./Can.upt', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0906.11.90', 'Neither crushed nor ground:Cinnamon (Cinnamo. Zeylan. Blume), Excl. Wr./Can.up', 25, 20, 0, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0906.19.10', 'Cinnamon and cinnamon-tree flowers., NES Wrapped/canned upto 2.5 kg', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0906.19.90', 'Cinnamon and cinnamon-tree flowers., NES Excl. Wrapped/canned upto 2.5 kg', 25, 20, 0, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0906.20.00', 'Cinnamon And Cinnamon-Tree Flowers, Crushed Or Ground', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0907.10.10', 'Cloves (whole fruit, cloves and stems), Neither Crushed or ground, Wrapped/canned upto 2', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0907.10.90', 'Cloves (whole fruit, cloves and stems), Neither Crushed or ground, EXCL. Wrapped/canned', 25, 20, 0, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0907.20.10', 'Cloves (whole fruit, cloves and stems), Crushed or grCloves (whole fruit, cloves and stems), Crushed or ground, Wrapped/canned upto 2.5 Kg', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0907.20.90', 'Cloves (whole fruit, cloves and stems), Crushed or ground, EXCL. Wrapped/canned upto 2.5', 25, 20, 0, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0908.11.10', 'Nutmeg :Neither Crushed or ground, Wrapped/canned upto 2.5 Kg', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0908.11.90', 'Nutmeg :Neither Crushed or ground, EXCL. Wrapped/canned upto 2.5 Kg', 25, 0, 0, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0908.12.10', 'Nutmeg : Crushed or ground, Wrapped/canned upto 2.5 Kg', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0908.12.90', 'Nutmeg : Crushed or ground, EXCL. Wrapped/canned upto 2.5 Kg', 25, 0, 0, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0908.21.10', 'Mace : Neither Crushed or ground, Wrapped/canned upto 2.5 Kg', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0908.21.90', 'Mace : Neither Crushed or ground, EXCL. Wrapped/canned upto 2.5 Kg', 25, 0, 0, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0908.22.10', 'Mace : Crushed or ground, Wrapped/canned upto 2.5 Kg', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0908.22.90', 'Mace : Crushed or ground, EXCL. Wrapped/canned upto 2.5 Kg', 25, 0, 0, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0908.31.10', 'Cardamoms :Neither Crushed or ground. Wrapped/canned upto 2.5 Kg', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0206.29.10', 'Frozen Edible Bovine Offal (Excl. Tongues And Livers), Wrapped/Canned upto 2.5 kg', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0206.29.90', 'Frozen Edible Bovine Offal (Excl. Tongues And Livers), Nes', 25, 0, 0, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0206.30.10', 'Fresh Or Chilled Edible Swine Offal, Wrapped/Canned upto 2.5 kg', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('0802.31.10', 'Walnuts In Shell, Fresh Or Dried,Wrapped/Canned Upto 2.5kg', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('2712.20.10', 'Paraffin wax, containing <0.75% oil Imp by VAT reg tyre tube manufa ind', 15, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('2712.20.90', 'Paraffin wax, containing <0.75% oil excl. Imp by VAT reg tyre tube manufa ind', 15, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('2712.90.10', 'MICROCRYSTALLINE PETROLEUM WAX, SLACK WAX,OZOKERITE..,EXCL.PETROLEUM JELLY, PARAFFIN WAX', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('2712.90.20', 'Paraffin wax imported by VAT registered manufacturers', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('2403.99.00', 'OTHER MANUFACTURED TOBACCO AND MANUFACTURED TOBACCO..EXCL.HOMOGENISED OR RECONS.TOBACCO', 25, 150, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('2501.00.10', 'Pure Sodium Chloride Bp/Usp Pyrogen Free', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('2501.00.20', 'Salt (other than pure sodium chlo.)...solution ..salt boulder for crushing & salt in bul', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('2501.00.30', 'Rock salt, bhit lobon', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('2501.00.91', 'Denatured salt (coloured)', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('2501.00.99', 'Other Salt', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('2502.00.00', 'Unroasted Iron Pyrites', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('2503.00.00', 'Sulphur Of All Kinds (Excl. Sublimed, Precipitated And Colloidal Sulphur)', 0, 0, 0, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('2504.10.00', 'Natural Graphite In Powder Or In Flakes', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('2504.90.00', 'Other Natural Graphite (Excl. In Powder Or In Flakes)', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4101.90.00', 'OTHER, INCLUDING BUTTS, BENDS AND BELLIES', 5, 0, 0, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4102.10.00', 'Raw Skins Of Sheep Or Lambs, With Wool On', 5, 0, 0, 
    2, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4102.21.00', 'Raw Pickled Skins Of Sheep Or Lambs, Without Wool, Not Tanned', 5, 0, 0, 
    2, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4102.29.00', 'Raw Skins Of Sheep Or Lambs, Without Wool, Not Pickled, Not Tanned', 5, 0, 0, 
    2, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4103.20.00', 'Raw Hides And Skins Of Reptiles, Fresh Or Preserved, Not Tanned', 5, 0, 0, 
    2, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('5305.00.90', 'Coconut, avaca.... Excl. Coco substrate; coco pellet; growing media', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('5306.10.00', 'Single Flax Yarn', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('5306.20.00', 'Multiple Or Cabled Flax Yarn', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('5307.10.00', 'Single yarn of jute or of other textile bast fibres of 53.03', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('5308.10.00', 'Coir Yarn', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('5308.20.00', 'True Hemp Yarn', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('5308.90.00', 'Yarn Of Vegetable Textile Fibres, Nes', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('5309.11.00', 'Bleached Or Unbleached, Woven Fabrics Of Flax, With >=85% Flax', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('5309.19.00', 'Woven Fabrics Of Flax, With >=85% Flax, Printed, Dyed Or Coloured', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('5801.10.00', 'Woven Pile Fabrics And Chenille Fabrics Of Wool Or Fine Animal Hair', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('5801.21.00', 'UNCUT WEFT PILE FABRICS', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4419.19.00', 'Other, excl. Bread boards, chopping boards aOther, excl. Bread boards, chopping boards and similar boards & Chopsticks', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4419.90.00', 'Other, excl. Bamboo', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4420.10.00', 'Statuettes And Other Ornaments, Of Wood', 25, 20, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4420.90.00', 'Wood Marquetry, Inlaid Wood; Caskets & Cases For Jewellery/Cutlery Of Wood', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4421.10.00', 'Clothes Hangers Of Wood', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4421.91.00', 'Of bamboo', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4421.99.10', 'Other', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4421.99.20', 'Sliver/spinning can', 1, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4421.99.90', 'Other', 25, 0, 15, 
    5, 3, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4501.10.00', 'Natural Cork, Raw Or Simply Prepared', 10, 0, 0, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4501.90.00', 'Waste Cork; Crushed, Granulated Or Ground Cork', 10, 0, 0, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4407.12.00', 'Wood sawn or chipped lengthwise, sliced -- of fir(Abies spp) and spruce (Picea spp)', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4407.19.00', 'Wood sawn or chipped lengthwise, slic -- of a thickness exce 6 mm. Coniferous Other', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4407.21.00', 'Mahogany (Swietenia spp.)', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4407.22.00', 'Virola, Imbuia and Balsa', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4407.25.00', 'Tropical Wood Of Dark Red Meranti, Light Red Meranti & Meranti Bakau', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4407.26.00', 'Tropical Wood Of White Lauan,White Meranti,White Seraya,Yellow Meranti & Alan', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4407.27.00', 'Sapelli', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4407.28.00', 'Iroko', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4407.29.00', 'Other Tropical Wood not specified in Subheading Note 2', 5, 0, 0, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4407.91.00', 'Oak Wood (Quercus Spp.) Sawn/Chipped Lengthwise Sliced Or Peeled >6m Thick', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4407.92.00', 'Beech Wood (Fagus Spp.) Sawn/Chipped Lengthwise Sliced Or Peeled >6m Thick', 5, 0, 0, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4407.93.00', 'Wood sawn or chipped lengthwise, sliced or peeled,..exceeding 6 mm. Of maple (', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4407.94.00', 'Wood sawn or chipped lengthwise, sliced or peeled,..exceeding 6 mm.Of cherry (', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4407.95.00', 'Wood sawn or chipped lengthwise, sliced or peeled,..exceeding 6 mm. Of ash (Fr', 5, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4502.00.00', 'Natural Cork, Debacked Or Roughly Squared..., Etc', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4503.10.00', 'CORKS AND STOPPERS', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4503.90.00', 'Articles Of Natural Cork, Nes', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4504.10.00', 'Blocks..., Tiles Of Any Shape, Solid Cylinders, Of Agglomerated Cork', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4504.90.00', 'OTH, AGGLOMERATED CORK(WITH OR WITHOUT A BINDING SUB-STANCE) AND ARTICLES OF AGG. CORK', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4601.21.00', 'Mats, matting and screens of vegetable materials Of bamboo', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4601.22.00', 'Mats, matting and screens of vegetable materials Of rattan', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4601.29.00', 'Mats, matting and screens of vegetable materials, Excl. materials of bamboo &', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4601.92.00', 'Mats, matting and screens of vegetable materials, NES Of bamboo', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
Insert into HSCODE_INFO_P
   (HSCODE, DESCRIPTION, CD, SD, VAT, 
    AIT, RD, ATV, USER1, YEAR, 
    TTI, COMPANY_ID)
 Values
   ('4601.93.00', 'Mats, matting and screens of vegetable materials, NES Of rattan', 10, 0, 15, 
    5, 0, 5, NULL, '2022-2023', 
    NULL, 3);
COMMIT;
