DROP USER TRADE CASCADE;
CREATE USER TRADE IDENTIFIED BY TRADE19;




GRANT SELECT ON SYS.USER$ TO  TRADE;
GRANT DBA TO  TRADE;
GRANT connect, resource, DBA TO TRADE;
ALTER USER  TRADE DEFAULT ROLE ALL;
GRANT UNLIMITED TABLESPACE TO  TRADE;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO  TRADE;
GRANT SELECT ON SYS.USER$ TO  TRADE;
GRANT SELECT ON SYS.V_$MYSTAT TO  TRADE;
GRANT SELECT ON SYS.V_$SESSION TO  TRADE;
/

---IF APEX INSTALLED THE USE IT----
ALTER USER  TRADE GRANT CONNECT THROUGH ORDS_PUBLIC_USER;
/