CREATE USER TRADE IDENTIFIED BY TRADE19;
CREATE USER TRADE IDENTIFIED BY TRADE19;


DROP USER DOCUMENTS CASCADE;
CREATE USER DOCUMENTS IDENTIFIED BY DOC19;




GRANT SELECT ON SYS.USER$ TO  DOCUMENTS;
GRANT DBA TO  DOCUMENTS;
GRANT connect, resource, DBA TO DOCUMENTS;
ALTER USER  DOCUMENTS DEFAULT ROLE ALL;
GRANT UNLIMITED TABLESPACE TO  DOCUMENTS;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO  DOCUMENTS;
GRANT SELECT ON SYS.USER$ TO  DOCUMENTS;
GRANT SELECT ON SYS.V_$MYSTAT TO  DOCUMENTS;
GRANT SELECT ON SYS.V_$SESSION TO  DOCUMENTS;
/

---IF APEX INSTALLED THE USE IT----
ALTER USER  DOCUMENTS GRANT CONNECT THROUGH ORDS_PUBLIC_USER;
/

alter user apex_220200 identified by 123 account unlock;
/

