----Create DB Link----
CREATE DATABASE LINK SalesLNK
    CONNECT TO SALES IDENTIFIED BY SALES7
    USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=119.148.46.181)(PORT=1521)) (CONNECT_DATA=(SERVICE_NAME=MATIN)))';

---Drop DB Link---
DROP DATABASE LINK SalesLNK;